# Generated by Django 3.1.3 on 2020-11-25 07:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0004_auto_20201125_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='toy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='toy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
