# Generated by Django 3.1.3 on 2020-11-29 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0006_auto_20201129_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='toy',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
