# Generated by Django 3.1.3 on 2020-12-05 05:13

from django.db import migrations, models
import toys.models


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0011_auto_20201204_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='toy',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=toys.models.photo_upload_path),
        ),
        migrations.AddField(
            model_name='toy',
            name='type',
            field=models.CharField(blank=True, choices=[('animals', 'Animals'), ('dolls', 'Dolls'), ('cars', 'Cars'), ('educational_toys', 'Educational Toys'), ('electronic_toys', 'Electronic Toys')], max_length=16, null=True),
        ),
    ]
