# Generated by Django 3.1.3 on 2021-01-09 17:06

from django.db import migrations, models
import toys.models


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0012_auto_20201205_0513'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=toys.models.user_photo_upload_path),
        ),
    ]
